package engine_test

import (
	"context"
	"errors"
	"github.com/nvrakesh06/ai-agentic-harness/internal/demo"
	"github.com/nvrakesh06/ai-agentic-harness/internal/engine"
	"github.com/nvrakesh06/ai-agentic-harness/internal/provider"
	"os"
	"path/filepath"
	"testing"
	"time"
)

type reviewInvocation struct {
	directory string
	artifact  bool
}

// emittingReviewer simulates a diagnostic such as tsc that writes a generated
// file despite being assigned a read-only review role. It deliberately waits so
// the test can inspect the disposable checkout before cancellation exercises
// failure cleanup.
type emittingReviewer struct {
	delegate provider.Provider
	started  chan reviewInvocation
	release  <-chan struct{}
	fail     bool
}

func (p *emittingReviewer) Name() string { return p.delegate.Name() }
func (p *emittingReviewer) Validate(ctx context.Context) error {
	return p.delegate.Validate(ctx)
}
func (p *emittingReviewer) Run(ctx context.Context, request provider.Request) (provider.Result, error) {
	if request.Role != "reviewer" {
		return p.delegate.Run(ctx, request)
	}
	_, artifactErr := os.Stat(filepath.Join(request.Directory, "feature-isolated-review.txt"))
	if err := os.WriteFile(filepath.Join(request.Directory, "diagnostic-emitted.js"), []byte("generated by a read-only diagnostic\n"), 0600); err != nil {
		return provider.Result{}, err
	}
	p.started <- reviewInvocation{directory: request.Directory, artifact: artifactErr == nil}
	select {
	case <-p.release:
		if p.fail {
			return provider.Result{}, errors.New("injected reviewer failure after diagnostic emission")
		}
		return provider.Result{Schema: 1, Status: "completed", Summary: "diagnostic inspected the disposable checkout"}, nil
	case <-ctx.Done():
		return provider.Result{}, ctx.Err()
	}
}

func TestReadOnlyReviewerEmissionUsesDisposableCheckoutAndCleansIt(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 150*time.Second)
	defer cancel()
	f, err := demo.New(ctx, t.TempDir(), []string{"git", "diff", "--exit-code"})
	if err != nil {
		t.Fatal(err)
	}
	defer f.P.DB.Close()

	release := make(chan struct{})
	emitter := &emittingReviewer{delegate: f.Provider, started: make(chan reviewInvocation, 1), release: release, fail: true}
	f.P.Provider = emitter
	seedReadyTask(t, ctx, f, "isolated-review")

	done := make(chan error, 1)
	go func() { done <- engine.New(f.P).Serve(ctx) }()
	var invocation reviewInvocation
	select {
	case invocation = <-emitter.started:
	case err := <-done:
		t.Fatalf("supervisor stopped before reviewer emission: %v", err)
	case <-ctx.Done():
		t.Fatal(ctx.Err())
	}
	if !invocation.artifact {
		t.Fatal("reviewer did not receive the implemented artifact in its checkout")
	}
	if _, err := os.Stat(filepath.Join(invocation.directory, "diagnostic-emitted.js")); err != nil {
		t.Fatalf("emitting reviewer file missing from disposable checkout: %v", err)
	}
	snapshot, _, err := f.P.DB.Load()
	if err != nil {
		t.Fatal(err)
	}
	writer := f.P.TaskPath(snapshot.Tasks["isolated-review"])
	if invocation.directory == writer {
		t.Fatal("read-only reviewer was given the writer worktree")
	}
	if _, err := os.Stat(filepath.Join(writer, "diagnostic-emitted.js")); !os.IsNotExist(err) {
		t.Fatalf("read-only diagnostic dirtied writer worktree: %v", err)
	}

	// An error after emission must still discard the AIH-owned detached checkout,
	// including its generated file.
	close(release)
	deadline := time.After(15 * time.Second)
	for {
		if _, err := os.Stat(invocation.directory); os.IsNotExist(err) {
			break
		} else if err != nil {
			t.Fatalf("inspect disposable reviewer checkout cleanup: %v", err)
		}
		select {
		case <-time.After(50 * time.Millisecond):
		case <-deadline:
			t.Fatalf("disposable reviewer checkout was not cleaned after failure")
		case <-ctx.Done():
			t.Fatal(ctx.Err())
		}
	}
	if _, err := os.Stat(filepath.Join(writer, "diagnostic-emitted.js")); !os.IsNotExist(err) {
		t.Fatalf("writer worktree became dirty after reviewer cleanup: %v", err)
	}
	cancel()
	<-done
}

func TestDisposableReviewWorktreeCleanupRejectsJunctionAndDiscardsGeneratedFiles(t *testing.T) {
	ctx := context.Background()
	f, err := demo.New(ctx, t.TempDir(), []string{"git", "diff", "--exit-code"})
	if err != nil {
		t.Fatal(err)
	}
	defer f.P.DB.Close()
	runID := "generated-diagnostic"
	dir, err := f.P.ValidDisposableReviewWorktreePath(runID)
	if err != nil {
		t.Fatal(err)
	}
	if err = f.P.Git.Detached(ctx, dir, "refs/remotes/origin/main"); err != nil {
		t.Fatal(err)
	}
	if err = os.WriteFile(filepath.Join(dir, "emitted.js"), []byte("diagnostic output\n"), 0600); err != nil {
		t.Fatal(err)
	}
	if err = f.P.RemoveDisposableReviewWorktree(ctx, runID); err != nil {
		t.Fatalf("remove generated disposable review worktree: %v", err)
	}
	if _, err = os.Stat(dir); !os.IsNotExist(err) {
		t.Fatalf("disposable review worktree remains after cleanup: %v", err)
	}

	root := filepath.Join(f.P.Dir, "review-worktrees")
	outside := filepath.Join(t.TempDir(), "outside")
	marker := filepath.Join(outside, "marker")
	if err = os.MkdirAll(outside, 0700); err != nil {
		t.Fatal(err)
	}
	if err = os.WriteFile(marker, []byte("must remain"), 0600); err != nil {
		t.Fatal(err)
	}
	if err = os.RemoveAll(root); err != nil {
		t.Fatal(err)
	}
	if err = os.Symlink(outside, root); err != nil {
		t.Skipf("junction fixture unavailable on this machine: %v", err)
	}
	if _, err = f.P.ValidDisposableReviewWorktreePath("swapped-root"); err == nil {
		t.Fatal("review root junction was accepted")
	}
	if err = f.P.RemoveDisposableReviewWorktree(ctx, "swapped-root"); err == nil {
		t.Fatal("review root junction was accepted for forced cleanup")
	}
	if _, err = os.Stat(marker); err != nil {
		t.Fatalf("review worktree cleanup affected outside marker: %v", err)
	}
}
