package engine_test

import (
	"context"
	"errors"
	"github.com/nvrakesh06/ai-agentic-harness/internal/demo"
	"github.com/nvrakesh06/ai-agentic-harness/internal/engine"
	"github.com/nvrakesh06/ai-agentic-harness/internal/gitx"
	"github.com/nvrakesh06/ai-agentic-harness/internal/provider"
	"os"
	"path/filepath"
	"testing"
	"time"
)

type reviewInvocation struct {
	directory string
	artifact  bool
	role      string
}

// emittingReviewer simulates a diagnostic such as tsc that writes a generated
// file despite being assigned a read-only review role. It deliberately waits so
// the test can inspect the disposable checkout before cancellation exercises
// failure cleanup.
type emittingReviewer struct {
	delegate provider.Provider
	worker   *demo.Worker
	started  chan reviewInvocation
	release  <-chan struct{}
	fail     bool
}

func (p *emittingReviewer) Name() string { return p.delegate.Name() }
func (p *emittingReviewer) Validate(ctx context.Context) error {
	return p.delegate.Validate(ctx)
}
func (p *emittingReviewer) Run(ctx context.Context, request provider.Request) (provider.Result, error) {
	if request.Role != "reviewer" && request.Role != "security" {
		return p.delegate.Run(ctx, request)
	}
	active := p.worker.ReviewActive.Add(1)
	defer p.worker.ReviewActive.Add(-1)
	for {
		previous := p.worker.ReviewMax.Load()
		if active <= previous || p.worker.ReviewMax.CompareAndSwap(previous, active) {
			break
		}
	}
	artifact := false
	if request.Role == "reviewer" {
		_, artifactErr := os.Stat(filepath.Join(request.Directory, "feature-isolated-review.txt"))
		artifact = artifactErr == nil
	}
	if err := os.WriteFile(filepath.Join(request.Directory, "diagnostic-"+request.Role+".js"), []byte("generated by a read-only diagnostic\n"), 0600); err != nil {
		return provider.Result{}, err
	}
	p.started <- reviewInvocation{directory: request.Directory, artifact: artifact, role: request.Role}
	select {
	case <-p.release:
		if p.fail && request.Role == "reviewer" {
			return provider.Result{}, errors.New("injected reviewer failure after diagnostic emission")
		}
		return provider.Result{Schema: 1, Status: "completed", Summary: "diagnostic inspected the disposable checkout"}, nil
	case <-ctx.Done():
		return provider.Result{}, ctx.Err()
	}
}

func TestReadOnlyReviewerEmissionUsesDisposableCheckoutAndCleansIt(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 150*time.Second)
	defer cancel()
	f, err := demo.New(ctx, t.TempDir(), []string{"git", "diff", "--exit-code"})
	if err != nil {
		t.Fatal(err)
	}
	defer f.P.DB.Close()

	release := make(chan struct{})
	emitter := &emittingReviewer{delegate: f.Provider, worker: f.Provider, started: make(chan reviewInvocation, 2), release: release, fail: true}
	f.P.Provider = emitter
	seedReadyTask(t, ctx, f, "isolated-review")
	snapshot, stateHead, err := f.P.Git.Load(ctx)
	if err != nil {
		t.Fatal(err)
	}
	snapshot.Tasks["isolated-review"].Security = true
	next, err := f.P.Git.StateCommit(ctx, stateHead, snapshot)
	if err != nil {
		t.Fatal(err)
	}
	if err = f.P.Git.Publish(ctx, []gitx.Update{{Branch: "aih-state", Old: stateHead, New: next}}); err != nil {
		t.Fatal(err)
	}

	done := make(chan error, 1)
	go func() { done <- engine.New(f.P).Serve(ctx) }()
	supervisorStopped := false
	defer func() {
		if supervisorStopped {
			return
		}
		cancel()
		select {
		case <-done:
		case <-time.After(5 * time.Second):
			t.Error("supervisor did not drain after read-only fixture failure")
		}
	}()
	invocations := map[string]reviewInvocation{}
	for len(invocations) < 2 {
		select {
		case invocation := <-emitter.started:
			invocations[invocation.role] = invocation
		case err := <-done:
			supervisorStopped = true
			t.Fatalf("supervisor stopped before independent reviewer wave: %v", err)
		case <-ctx.Done():
			t.Fatal(ctx.Err())
		}
	}
	invocation, ok := invocations["reviewer"]
	if !ok || invocations["security"].directory == "" {
		t.Fatalf("independent reviewer wave omitted a required peer: %#v", invocations)
	}
	if !invocation.artifact {
		t.Fatal("reviewer did not receive the implemented artifact in its checkout")
	}
	for role, invocation := range invocations {
		if _, err := os.Stat(filepath.Join(invocation.directory, "diagnostic-"+role+".js")); err != nil {
			t.Fatalf("emitting %s file missing from disposable checkout: %v", role, err)
		}
	}
	snapshot, _, err = f.P.DB.Load()
	if err != nil {
		t.Fatal(err)
	}
	writer := f.P.TaskPath(snapshot.Tasks["isolated-review"])
	if invocation.directory == writer {
		t.Fatal("read-only reviewer was given the writer worktree")
	}
	for role := range invocations {
		if _, err := os.Stat(filepath.Join(writer, "diagnostic-"+role+".js")); !os.IsNotExist(err) {
			t.Fatalf("read-only %s diagnostic dirtied writer worktree: %v", role, err)
		}
	}
	deadlineForPeer := time.After(5 * time.Second)
	for f.Provider.ReviewMax.Load() < int32(f.Project.MaxReaders) {
		select {
		case <-time.After(10 * time.Millisecond):
		case <-deadlineForPeer:
			t.Fatalf("read-only reviewers did not retain configured parallelism: got %d want %d", f.Provider.ReviewMax.Load(), f.Project.MaxReaders)
		}
	}

	// An error after emission must still discard the AIH-owned detached checkout,
	// including its generated file.
	close(release)
	deadline := time.After(15 * time.Second)
	for role, invocation := range invocations {
		for {
			if _, err := os.Stat(invocation.directory); os.IsNotExist(err) {
				break
			} else if err != nil {
				t.Fatalf("inspect %s disposable checkout cleanup: %v", role, err)
			}
			select {
			case <-time.After(50 * time.Millisecond):
			case <-deadline:
				t.Fatalf("%s disposable reviewer checkout was not cleaned after failure", role)
			case <-ctx.Done():
				t.Fatal(ctx.Err())
			}
		}
	}
	for role := range invocations {
		if _, err := os.Stat(filepath.Join(writer, "diagnostic-"+role+".js")); !os.IsNotExist(err) {
			t.Fatalf("writer worktree became dirty after %s cleanup: %v", role, err)
		}
	}
	cancel()
	select {
	case <-done:
		supervisorStopped = true
	case <-time.After(5 * time.Second):
		t.Fatal("supervisor did not drain after reviewer failure cancellation")
	}
}

func TestDisposableReviewWorktreeCleanupRejectsJunctionAndDiscardsGeneratedFiles(t *testing.T) {
	ctx := context.Background()
	f, err := demo.New(ctx, t.TempDir(), []string{"git", "diff", "--exit-code"})
	if err != nil {
		t.Fatal(err)
	}
	defer f.P.DB.Close()
	runID := "generated-diagnostic"
	dir, err := f.P.ValidDisposableReviewWorktreePath(runID)
	if err != nil {
		t.Fatal(err)
	}
	if err = f.P.Git.Detached(ctx, dir, "refs/remotes/origin/main"); err != nil {
		t.Fatal(err)
	}
	if err = os.WriteFile(filepath.Join(dir, "emitted.js"), []byte("diagnostic output\n"), 0600); err != nil {
		t.Fatal(err)
	}
	if err = f.P.RemoveDisposableReviewWorktree(ctx, runID); err != nil {
		t.Fatalf("remove generated disposable review worktree: %v", err)
	}
	if _, err = os.Stat(dir); !os.IsNotExist(err) {
		t.Fatalf("disposable review worktree remains after cleanup: %v", err)
	}

	root := filepath.Join(f.P.Dir, "review-worktrees")
	outside := filepath.Join(t.TempDir(), "outside")
	marker := filepath.Join(outside, "marker")
	if err = os.MkdirAll(outside, 0700); err != nil {
		t.Fatal(err)
	}
	if err = os.WriteFile(marker, []byte("must remain"), 0600); err != nil {
		t.Fatal(err)
	}
	if err = os.RemoveAll(root); err != nil {
		t.Fatal(err)
	}
	if err = os.Symlink(outside, root); err != nil {
		t.Skipf("junction fixture unavailable on this machine: %v", err)
	}
	if _, err = f.P.ValidDisposableReviewWorktreePath("swapped-root"); err == nil {
		t.Fatal("review root junction was accepted")
	}
	if err = f.P.RemoveDisposableReviewWorktree(ctx, "swapped-root"); err == nil {
		t.Fatal("review root junction was accepted for forced cleanup")
	}
	if _, err = os.Stat(marker); err != nil {
		t.Fatalf("review worktree cleanup affected outside marker: %v", err)
	}
}

func TestDisposableAnalysisWorktreeCleanupDiscardsGeneratedFiles(t *testing.T) {
	ctx := context.Background()
	f, err := demo.New(ctx, t.TempDir(), []string{"git", "diff", "--exit-code"})
	if err != nil {
		t.Fatal(err)
	}
	defer f.P.DB.Close()
	runID := "generated-analysis-diagnostic"
	dir, err := f.P.ValidDisposableAnalysisWorktreePath(runID)
	if err != nil {
		t.Fatal(err)
	}
	if err = f.P.Git.Detached(ctx, dir, "refs/remotes/origin/main"); err != nil {
		t.Fatal(err)
	}
	if err = os.WriteFile(filepath.Join(dir, "analysis-emitted.js"), []byte("orchestrator diagnostic output\n"), 0600); err != nil {
		t.Fatal(err)
	}
	if err = f.P.RemoveDisposableAnalysisWorktree(ctx, runID); err != nil {
		t.Fatalf("remove generated disposable analysis worktree: %v", err)
	}
	if _, err = os.Stat(dir); !os.IsNotExist(err) {
		t.Fatalf("disposable analysis worktree remains after forced cleanup: %v", err)
	}
	if err = f.P.RemoveDisposableAnalysisWorktree(ctx, "../outside"); err == nil {
		t.Fatal("unsafe analysis worktree identifier was accepted for forced cleanup")
	}
}
