// Package service renders a user service around the existing foreground CLI.
// It does not change leases, task recovery, credentials, or the state schema.
package service

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
)

type Options struct {
	Name, Binary, Repository, Home, EnvironmentFile, Path string
}

func Render(o Options) (string, error) {
	if !regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$`).MatchString(o.Name) {
		return "", fmt.Errorf("service name must be 1..64 letters, digits, underscores or hyphens")
	}
	paths := []string{o.Binary, o.Repository, o.Home}
	if o.EnvironmentFile != "" {
		paths = append(paths, o.EnvironmentFile)
	}
	for _, path := range paths {
		if !filepath.IsAbs(path) || strings.ContainsAny(path, "\x00\r\n\t") || strings.TrimSpace(path) != path {
			return "", fmt.Errorf("service paths must be absolute with no control characters or surrounding whitespace")
		}
	}
	if strings.HasSuffix(o.Repository, `\`) {
		return "", fmt.Errorf("working directory cannot end with a unit-file line continuation")
	}
	if strings.ContainsAny(o.Path, "\x00\r\n\t") {
		return "", fmt.Errorf("invalid service PATH")
	}
	args := []string{o.Binary, "--repo", o.Repository, "--home", o.Home}
	if o.EnvironmentFile != "" {
		args = append(args, "--env-file", o.EnvironmentFile)
	}
	args = append(args, "start", "--foreground")
	for i := range args {
		// systemd expands environment variables in arguments, not the executable.
		args[i] = quote(args[i], i != 0)
	}
	return fmt.Sprintf(`# Generated by aih service install. Runs as the owning, non-root OS user.
[Unit]
Description=AIH supervisor (%s)
StartLimitIntervalSec=0

[Service]
Type=exec
WorkingDirectory=%s
Environment=%s
ExecStart=%s
Restart=on-failure
RestartSec=15s
TimeoutStopSec=180s
KillMode=mixed
UMask=0077
StandardOutput=journal
StandardError=journal
SyslogIdentifier=aih-%s

[Install]
WantedBy=default.target
`, o.Name, strings.ReplaceAll(o.Repository, "%", "%%"), quote("PATH="+o.Path, false), strings.Join(args, " "), o.Name), nil
}

func quote(s string, command bool) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "%", "%%")
	if command {
		s = strings.ReplaceAll(s, "$", "$$")
	}
	return `"` + s + `"`
}
